# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import subtitling_pb2 as subtitling__pb2


class SubtitlingStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_stream(
                '/sftpprocessor.Subtitling/Transcribe',
                request_serializer=subtitling__pb2.TranscriptionRequest.SerializeToString,
                response_deserializer=subtitling__pb2.TranscriptionReply.FromString,
                )


class SubtitlingServicer(object):
    """The greeting service definition.
    """

    def Transcribe(self, request, context):
        """Starts a transcription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubtitlingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=subtitling__pb2.TranscriptionRequest.FromString,
                    response_serializer=subtitling__pb2.TranscriptionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sftpprocessor.Subtitling', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Subtitling(object):
    """The greeting service definition.
    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sftpprocessor.Subtitling/Transcribe',
            subtitling__pb2.TranscriptionRequest.SerializeToString,
            subtitling__pb2.TranscriptionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
