# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subtitling.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10subtitling.proto\x12\rsftpprocessor\"}\n\x0eRequestHeaders\x12;\n\x07headers\x18\x05 \x03(\x0b\x32*.sftpprocessor.RequestHeaders.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x81\x02\n\x14TranscriptionRequest\x12\x1e\n\x11\x65xternalReference\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tsourceUrl\x18\x02 \x01(\t\x12-\n\x06\x66ormat\x18\x03 \x03(\x0e\x32\x1d.sftpprocessor.SubtitleFormat\x12\x30\n\x0foutputLanguages\x18\x04 \x03(\x0e\x32\x17.sftpprocessor.Language\x12\x33\n\x07headers\x18\x05 \x01(\x0b\x32\x1d.sftpprocessor.RequestHeadersH\x01\x88\x01\x01\x42\x14\n\x12_externalReferenceB\n\n\x08_headers\"\xed\x01\n\x12TranscriptionReply\x12\x1e\n\x11\x65xternalReference\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x10transcriptionUrl\x18\x02 \x01(\t\x12\x32\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x1d.sftpprocessor.SubtitleFormatH\x01\x88\x01\x01\x12)\n\x08language\x18\x04 \x01(\x0e\x32\x17.sftpprocessor.Language\x12\x10\n\x08original\x18\x05 \x01(\x08\x12\x0b\n\x03\x63id\x18\x06 \x01(\tB\x14\n\x12_externalReferenceB\t\n\x07_format*\"\n\x0eSubtitleFormat\x12\x07\n\x03VTT\x10\x00\x12\x07\n\x03SRT\x10\x01*<\n\x08Language\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02\x45N\x10\x01\x12\x06\n\x02\x44\x45\x10\x02\x12\x06\n\x02\x46R\x10\x03\x12\x06\n\x02IT\x10\x04\x12\x06\n\x02\x45S\x10\x05\x32\x66\n\nSubtitling\x12X\n\nTranscribe\x12#.sftpprocessor.TranscriptionRequest\x1a!.sftpprocessor.TranscriptionReply\"\x00\x30\x01\x42K\n0ch.swisstxt.citizenjournalist.sftpprocessor.grpcB\x0fSubtitlingProtoP\x01\xa2\x02\x03STPb\x06proto3')

_SUBTITLEFORMAT = DESCRIPTOR.enum_types_by_name['SubtitleFormat']
SubtitleFormat = enum_type_wrapper.EnumTypeWrapper(_SUBTITLEFORMAT)
_LANGUAGE = DESCRIPTOR.enum_types_by_name['Language']
Language = enum_type_wrapper.EnumTypeWrapper(_LANGUAGE)
VTT = 0
SRT = 1
NONE = 0
EN = 1
DE = 2
FR = 3
IT = 4
ES = 5


_REQUESTHEADERS = DESCRIPTOR.message_types_by_name['RequestHeaders']
_REQUESTHEADERS_HEADERSENTRY = _REQUESTHEADERS.nested_types_by_name['HeadersEntry']
_TRANSCRIPTIONREQUEST = DESCRIPTOR.message_types_by_name['TranscriptionRequest']
_TRANSCRIPTIONREPLY = DESCRIPTOR.message_types_by_name['TranscriptionReply']
RequestHeaders = _reflection.GeneratedProtocolMessageType('RequestHeaders', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTHEADERS_HEADERSENTRY,
    '__module__' : 'subtitling_pb2'
    # @@protoc_insertion_point(class_scope:sftpprocessor.RequestHeaders.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _REQUESTHEADERS,
  '__module__' : 'subtitling_pb2'
  # @@protoc_insertion_point(class_scope:sftpprocessor.RequestHeaders)
  })
_sym_db.RegisterMessage(RequestHeaders)
_sym_db.RegisterMessage(RequestHeaders.HeadersEntry)

TranscriptionRequest = _reflection.GeneratedProtocolMessageType('TranscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPTIONREQUEST,
  '__module__' : 'subtitling_pb2'
  # @@protoc_insertion_point(class_scope:sftpprocessor.TranscriptionRequest)
  })
_sym_db.RegisterMessage(TranscriptionRequest)

TranscriptionReply = _reflection.GeneratedProtocolMessageType('TranscriptionReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPTIONREPLY,
  '__module__' : 'subtitling_pb2'
  # @@protoc_insertion_point(class_scope:sftpprocessor.TranscriptionReply)
  })
_sym_db.RegisterMessage(TranscriptionReply)

_SUBTITLING = DESCRIPTOR.services_by_name['Subtitling']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n0ch.swisstxt.citizenjournalist.sftpprocessor.grpcB\017SubtitlingProtoP\001\242\002\003STP'
  _REQUESTHEADERS_HEADERSENTRY._options = None
  _REQUESTHEADERS_HEADERSENTRY._serialized_options = b'8\001'
  _SUBTITLEFORMAT._serialized_start=662
  _SUBTITLEFORMAT._serialized_end=696
  _LANGUAGE._serialized_start=698
  _LANGUAGE._serialized_end=758
  _REQUESTHEADERS._serialized_start=35
  _REQUESTHEADERS._serialized_end=160
  _REQUESTHEADERS_HEADERSENTRY._serialized_start=114
  _REQUESTHEADERS_HEADERSENTRY._serialized_end=160
  _TRANSCRIPTIONREQUEST._serialized_start=163
  _TRANSCRIPTIONREQUEST._serialized_end=420
  _TRANSCRIPTIONREPLY._serialized_start=423
  _TRANSCRIPTIONREPLY._serialized_end=660
  _SUBTITLING._serialized_start=760
  _SUBTITLING._serialized_end=862
# @@protoc_insertion_point(module_scope)
